spring.application.name=backend

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/datashifter
spring.datasource.username=root
spring.datasource.password=rdr
spring.jpa.hibernate.ddl-auto=update

datashifter.migration.default-batch-size=1000
datashifter.migration.max-batch-size=10000

logging.level.com.dharmaraj.datashifter=INFO
